apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  selector:
    app: auth
    service: video-converter
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
